const update = require("./nav")
const productData = require("./productFactory")
const printProduct = require("./productController")
const printReview = require("./reviewController")
const reviewData = require("./reviewFactory")
update()
printProduct(productData)
printReview(reviewData)